### Variables
@apiurl = https://gorest.co.in/public-api 

### GET users
GET {{apiurl}}/users HTTP/1.1

### POST users
POST {{apiurl}}/users HTTP/1.1
Content-Type: application/json
Authorization: Bearer ACCESS-TOKEN

{
  "name":"Tenali Ramakrishna",
  "gender":"Male",
  "email":"tenali.ramakrishna@15ce.com",
  "status":"Active"
}

### GET categories
GET {{apiurl}}/categories HTTP/1.1
